import { Router } from "express";

const decoys = Router();

decoys.get('/fake/1', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/1/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/1/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/1', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/1/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/1/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/1', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/1/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/1', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/1/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/2', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/2/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/2/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/2', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/2/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/2/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/2', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/2/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/2', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/2/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/3', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/3/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/3/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/3', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/3/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/3/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/3', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/3/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/3', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/3/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/4', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/4/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/4/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/4', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/4/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/4/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/4', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/4/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/4', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/4/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/5', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/5/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/5/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/5', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/5/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/5/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/5', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/5/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/5', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/5/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/6', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/6/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/6/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/6', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/6/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/6/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/6', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/6/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/6', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/6/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/7', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/7/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/7/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/7', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/7/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/7/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/7', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/7/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/7', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/7/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/8', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/8/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/8/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/8', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/8/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/8/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/8', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/8/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/8', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/8/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/9', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/9/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/9/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/9', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/9/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/9/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/9', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/9/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/9', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/9/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

decoys.get('/fake/10', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/10/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.get('/fake/10/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/10', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/10/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.post('/fake/10/:fake/:fake_thing', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/10', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.put('/fake/10/:fake', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/10', (req, res) => { res.send({ message: 'decoy!'}) })
decoys.delete('/fake/10/:fake', (req, res) => { res.send({ message: 'decoy!'}) })

export default decoys;