http://localhost:3000

### Query params

http://localhost:3000/books?minPrice=200&maxPrice=300

### Bad query params

http://localhost:3000/books?minPrice=200&maxPrice=hello


###

http://localhost:3000/books/abfab189-cc71-4453-91ca-3c9d95b39bd1


### bad book id
http://localhost:3000/books/123


### POST a book
POST http://localhost:3000/books
content-type: application/json

{
  "title": "hello",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "price": 11.50
}


### decoy
http://localhost:3000/fake/2/hello