http://localhost:3000

###

http://localhost:3000/books?minPrice=200&maxPrice=300


###

http://localhost:3000/books/bf2f993c-80d1-498d-8a08-d5f5557a2188


### bad book id
http://localhost:3000/books/123


### POST a book
POST http://localhost:3000/books
content-type: application/json

{
  "title": "hello",
  "author": "F. Scott Fitzgerald",
  "genre": "Fiction",
  "price": 11.50
}


### decoy
http://localhost:3000/fake/1